name: Build & Push to Docker Hub and AWS ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Buildx setup (Docker images banane ke liye zaroori hai)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. Login to Docker Hub (Backup ke liye rakhte hain)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Configure AWS Credentials (IAM User ki keys use karega)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to Amazon ECR (Private Registry)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build and push to BOTH Docker Hub and AWS ECR
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tags mein dhyan dena, user-service wahi hona chahiye jo ECR mein banaya hai
          tags: |
            shaanyadav/user-service:latest
            ${{ steps.login-ecr.outputs.registry }}/user-service:latest